const sequelize = require("../../config/connection");
const { UserProfile } = require('../../models');

let generateSteps = async () => {
    try {
      await sequelize.transaction(async (t) => {
        let allUsersProfilesDB = await UserProfile.findAll();
        let allUserProfiles = allUsersProfilesDB.map((profile) => profile.get({plain: true}));
        let userChallenge = [];
        for (const userProfile of allUserProfiles) {
          userChallenge.push(userProfile.challenge);
          if (userProfile.challenge == "Challenge One") {
            autogeneratedStepCount = Math.floor(Math.random() * 2001) + 8000;
            //between 8 and 10 thousand
          }
          if (userProfile.challenge == "Challenge Two") {
            autogeneratedStepCount = Math.floor(Math.random() * 2001) + 6000;
            //between 6 and 8 thousand
          }
          if (userProfile.challenge == "Challenge Three") {
            autogeneratedStepCount = Math.floor(Math.random() * 2001) + 4000;
            //between 4 and 6 thousand
          }
          await UserProfile.update(
            {
              current_steps: autogeneratedStepCount,
            },
            {
              where: {
                user_id : userProfile.user_id
              }
            }
          )
        }
     });
    }
    catch (error) {
      console.error("Error in cron job:", error);
    }
  }

  generateSteps();